<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>33473cb1-0044-4a1a-b073-f2039d50a8d3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" Version="2.*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.8" />
  </ItemGroup>

</Project>
